# Generated by Django 5.1.6 on 2025-05-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekking_app', '0002_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('not_urgent', 'Not Urgent')], default='not_urgent', max_length=15),
        ),
    ]
