# Generated by Django 5.1.6 on 2025-06-05 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekking_app', '0005_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trekking_app.comment'),
        ),
    ]
